import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <div className={styles.logo_container}>
          <img className={styles.logo} src='/DYNABOX.png'></img>
        </div>

        <p className={styles.description}>
          THE AWESOME NFT EXCHANGE GAME
        </p>

        <h1 className={styles.title}>
          <button className={styles.pushable}>
            <span className={styles.shadow}></span>
            <span className={styles.edge}></span>
            <span className={styles.front}>
              <img className={styles.metamask_logo} src='/metamask-icon.png'></img>
              <span className={styles.button_text}>Connect Wallet</span>
            </span>
          </button>
        </h1>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>Locker &rarr;</h2>
            <p>Check your NFT items</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Gym &rarr;</h2>
            <p>Upgrade your habilities</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Ring &rarr;</h2>
            <p>Fight to gain NFT rewards</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Hachathon 2022
        </a>
      </footer>
    </div>
  )
}
